global using AluraAccessRPA.Application.Selenium;
global using AluraAccessRPA.Application.Selenium.Controllers;
global using AluraAccessRPA.Application.Selenium.Page;
global using AluraAccessRPA.Domain.Interfaces;
global using AluraAccessRPA.Infrastructure.Context;
global using AluraAccessRPA.Infrastructure.Data;
global using AluraAccessRPA.Infrastructure.Services;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using AluraAccessRPA.Domain.Entities;
global using AluraAccessRPA.Application.Selenium.Elements;
global using AluraAccessRPA.Application.Selenium.Extensions;
global using OpenQA.Selenium;
global using OpenQA.Selenium.Support.UI;
global using static System.TimeSpan;
